project:
  type: website

website:
  title: "my-portfolio"
  site-url: "https://logan-mather.github.io/my-portfolio/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

